version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.10.0-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package-lock.json" }}
            - dependency-cache-
      - run:
          name: install
          command: npm install
      - run:
          name: Lint
          command: npm run ng -- lint @yellowspot/ng-truncate
      - run:
          name: Unit Test
          command: npm run ng -- test --watch false @yellowspot/ng-truncate
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
