version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.4.0
  node: circleci/node@5.0

jobs:
  build:
    docker:
      - image: cimg/node:16.17.1-browsers
    steps:
      - browser-tools/install-chrome
      - checkout
      - node/install-packages
      - run:
          name: Lint
          command: npm run ng -- lint @yellowspot/ng-truncate
      - run:
          name: Unit Test
          command: npm run ng -- test --watch false @yellowspot/ng-truncate
